Metrics/BlockLength:
  Exclude:
    - Rakefile
    - '.bundle/**/*'
    - 'bin/**/*'
    - 'spec/**/*'
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Exclude:
    - 'spec/spec_helper.rb'
Naming/MethodParameterName:
  Enabled: false
Style/AccessModifierDeclarations:
  EnforcedStyle: 'inline'
AllCops:
  NewCops: enable
  SuggestExtensions: false
Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'
Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/spec_helper.rb'


